/** All event type constants — defined upfront to prevent conflicts in parallel worktrees */
export const EVENT_TYPES = {
  AGENT_REGISTERED: 'agent:registered',
  AGENT_METADATA_STORED: 'agent:metadata-stored',
  TASK_REQUESTED: 'task:requested',
  TASK_NEGOTIATED: 'task:negotiated',
  TASK_DELIVERED: 'task:delivered',
  TASK_ACCEPTED: 'task:accepted',
  TASK_REJECTED: 'task:rejected',
  TASK_EVALUATED: 'task:evaluated',
  PAYMENT_INITIATED: 'payment:initiated',
  PAYMENT_SETTLED: 'payment:settled',
  PAYMENT_FAILED: 'payment:failed',
  CIVIC_IDENTITY_CHECKED: 'civic:identity-checked',
  CIVIC_BEHAVIORAL_CHECKED: 'civic:behavioral-checked',
  CIVIC_FLAGGED: 'civic:flagged',
  CIVIC_CLEARED: 'civic:cleared',
  CIVIC_TOOL_BLOCKED: 'civic:tool-blocked',
  CIVIC_RESOLVED: 'civic:resolved',
  REPUTATION_COMPUTING: 'reputation:computing',
  REPUTATION_UPDATED: 'reputation:updated',
  REPUTATION_EXPLANATION_STORED: 'reputation:explanation-stored',
  FEEDBACK_SUBMITTED: 'feedback:submitted',
  FEEDBACK_RECORDED_ONCHAIN: 'feedback:recorded-onchain',
  DEMO_ACT_CHANGED: 'demo:act-changed',
  DEMO_RESET: 'demo:reset',
  DEMO_COMPLETE: 'demo:complete',
  ORCHESTRATOR_ROUTED: 'orchestrator:routed',
  ORCHESTRATOR_ROUTING_FAILED: 'orchestrator:routing-failed',
  LIFECYCLE_STARTED: 'lifecycle:started',
  LIFECYCLE_STEP_COMPLETED: 'lifecycle:step-completed',
  LIFECYCLE_COMPLETED: 'lifecycle:completed',
  LIFECYCLE_FAILED: 'lifecycle:failed',
  LIFECYCLE_PAYMENT_FAILED: 'lifecycle:payment-failed',
  LIFECYCLE_CIVIC_BLOCKED: 'lifecycle:civic-blocked',
  LIFECYCLE_NEGOTIATION_FAILED: 'lifecycle:negotiation-failed',
  LIVE_TRIGGER_STARTED: 'live:trigger-started',
  LIVE_TRIGGER_STEP: 'live:trigger-step',
  LIVE_TRIGGER_COMPLETED: 'live:trigger-completed',
  LIVE_TRIGGER_FAILED: 'live:trigger-failed',
  AGENT_DEPLOYED: 'agent:deployed',
  AGENT_DEPLOYED_HUMAN: 'agent:deployed-human',
  DEPLOYER_REPUTATION_LINKED: 'deployer:reputation-linked',
  DEPLOYER_SCORE_UPDATED: 'deployer:score-updated',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];
